# Generated by Django 3.0.2 on 2020-06-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(),
        ),
    ]
