# Generated by Django 3.0.2 on 2020-06-27 05:51

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('me_blog', '0003_auto_20200627_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
    ]
