# Generated by Django 3.0.2 on 2020-06-27 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('me_blog', '0004_auto_20200627_0551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='content',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='image',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='overview',
        ),
    ]
