# Generated by Django 3.0.2 on 2020-06-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me_blog', '0006_auto_20200627_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
