# Generated by Django 3.0.2 on 2020-06-27 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('me_blog', '0008_blogpost_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='content',
        ),
    ]
