# Generated by Django 3.0.2 on 2020-06-27 06:17

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('me_blog', '0010_blogpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=tinymce.models.HTMLField(default='test', verbose_name='Content'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='overview',
            field=models.TextField(default='test1', verbose_name='Content'),
            preserve_default=False,
        ),
    ]
