# Generated by Django 3.0.2 on 2020-06-27 06:23

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('me_blog', '0011_auto_20200627_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='overview',
            field=models.TextField(),
        ),
    ]
