# Generated by Django 3.0.2 on 2020-06-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me_blog', '0016_auto_20200627_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='me_blog.Category'),
        ),
    ]
