# Generated by Django 3.0.2 on 2020-06-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me_blog', '0017_blogpost_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageThing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
