# Generated by Django 3.0.2 on 2020-06-28 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('me_blog', '0019_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='next_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='me_blog.BlogPost'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='previous_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous', to='me_blog.BlogPost'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.CharField(default='test-post', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.ManyToManyField(to='me_blog.Category'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
