# Generated by Django 3.0.2 on 2020-06-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me_blog', '0020_auto_20200628_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='me_blog.Tags'),
        ),
    ]
