# Generated by Django 3.0.2 on 2020-06-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me_blog', '0021_blogpost_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='email_address',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tag',
            field=models.ManyToManyField(to='me_blog.Tags'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=200),
        ),
    ]
