# Generated by Django 3.0.2 on 2020-06-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me_blog', '0022_auto_20200628_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email_address',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
