# Generated by Django 3.0.2 on 2020-06-28 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('me_blog', '0024_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
