# Generated by Django 3.0.2 on 2020-06-29 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me_blog', '0027_tags_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
