# Generated by Django 3.0.2 on 2020-06-29 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me_blog', '0028_auto_20200629_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='link',
            field=models.CharField(max_length=300),
        ),
    ]
